#!/usr/bin/env python3
"""Split HunyuanWorld.yaml into conda-only deps + a pip requirements.txt.

The official environment file runs its whole pip section inside `conda env
create`, which buffers output and proved prone to hanging on wedged PyPI
connections. We install pip deps as our own Dockerfile step instead, so this
script regenerates the two derived files whenever HunyuanWorld.yaml changes:

    python docker/split-env.py

Outputs: docker/conda-base.yaml, docker/requirements.txt
Commented-out pip lines (the heavy compiled/git pkgs we build in dedicated
Dockerfile layers) are intentionally skipped.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(HERE, "HunyuanWorld.yaml")).read().splitlines()

conda_lines, pip_lines, in_pip = [], [], False
for ln in src:
    stripped = ln.strip()
    if stripped.startswith("- pip:"):
        in_pip = True
        continue
    if in_pip:
        if ln.startswith("prefix:"):
            in_pip = False
            conda_lines.append(ln)
            continue
        if stripped.startswith("#") or stripped == "":
            continue
        pkg = stripped[2:] if stripped.startswith("- ") else stripped
        pkg = pkg.split("#")[0].strip()
        if pkg:
            pip_lines.append(pkg)
    else:
        conda_lines.append(ln)

with open(os.path.join(HERE, "conda-base.yaml"), "w") as f:
    f.write("\n".join(conda_lines).rstrip() + "\n")

hdr = (
    "# AUTO-GENERATED by docker/split-env.py from HunyuanWorld.yaml — do not edit by hand.\n"
    "# Heavy compiled/git pkgs (flash-attn, natten, sageattention, pytorch3d, moge)\n"
    "# are installed in dedicated Dockerfile layers and are NOT listed here.\n"
)
with open(os.path.join(HERE, "requirements.txt"), "w") as f:
    f.write(hdr + "\n".join(pip_lines) + "\n")

print(f"conda-base.yaml: {len(conda_lines)} lines | requirements.txt: {len(pip_lines)} pkgs")
